# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Example add-on
version: "1.2.1"
slug: example
description: Example add-on
url: "https://github.com/sdegroot/ha-addons/tree/main/example"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "europe-west4-docker.pkg.dev/mail2notion-pro/private/test"
